# Docker Compose конфигурация для Telegram бота
# Sprint S1: Контейнеризация приложения

version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: systech-aidd-bot
    restart: unless-stopped

    # Переменные окружения из .env файла
    env_file:
      - .env

    # Монтирование volumes для персистентности данных
    volumes:
      # База данных SQLite
      - ./data:/app/data
      # Логи приложения
      - ./logs:/app/logs
      # Системный промпт (можно менять без пересборки образа)
      - ./prompts:/app/prompts:ro

    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Healthcheck (опционально)
    # healthcheck:
    #   test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('data/messages.db') else 1)"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

# Volumes для явного создания (опционально)
volumes:
  bot_data:
    driver: local
  bot_logs:
    driver: local
